# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #add custom private ssh key 
  config.ssh.insert_key = false
  config.ssh.private_key_path = [
    '~/.ssh/id_rsa_poc_k8s_ansible',
    '~/.vagrant.d/insecure_private_key'
  ]

  #replace insecure private key
  config.vm.provision 'file', 
    source: '~/.ssh/id_rsa_poc_k8s_ansible.pub', 
    destination: '~/.ssh/authorized_keys'

  config.vm.define "VM-ANSIBLE-K8s" do |ans|
    ans.vm.box = "centos/8"
    ans.vm.provision "file", source: "~/.ssh/id_rsa_poc_k8s_ansible", destination: "$HOME/.ssh/"
	  ans.vm.provision :shell, inline: "chmod 400 /home/vagrant/.ssh/id_rsa_poc_k8s_ansible"	

    ans.vm.provision "file", source: "~/.ssh/id_rsa_poc_k8s_ansible.pub", destination: "$HOME/.ssh/"
	  ans.vm.provision :shell, inline: "chmod 600 /home/vagrant/.ssh/id_rsa_poc_k8s_ansible.pub"	

    ans.vm.provision "file", source: "./k8s_config/.", destination: "/tmp/conf/"
    ans.vm.provision "shell", path: "./ansible.sh"
    
    ans.vm.hostname = 'VM-ANSIBLE-K8s'    
    ans.vm.provider "virtualbox" do |vb|
      vb.name = "VM-ANSIBLE-K8s"
      vb.memory = "512"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--nic1", "NAT", "--nictype1", "virtio"]
    end
  end
  
  (1..2).each do |i|
	config.vm.define "K8s-Master-#{i}" do |kubernetes_master|
	  kubernetes_master.vm.box = "centos/8"		
	  kubernetes_master.vm.network "private_network", ip: "10.0.0.1#{i}"
	  kubernetes_master.vm.hostname = "Master#{i}"
	  kubernetes_master.vm.provider "virtualbox" do |vb|
	    vb.name = "Master#{i}"
		  vb.customize ["modifyvm", :id, "--groups", "/Kubernetes"]
		  vb.memory = "2048"
	  end
	end
  end
  
  (1..3).each do |i|
    config.vm.define "K8s-Worker-#{i}" do |kubernetes_worker|
      kubernetes_worker.vm.box = "centos/8"
	  kubernetes_worker.vm.network "private_network", ip: "10.0.0.10#{i}"
	  kubernetes_worker.vm.hostname = "Worker-#{i}"
	  kubernetes_worker.vm.provider "virtualbox" do |vb|
	    vb.name = "Worker-#{i}"
		  vb.customize ["modifyvm", :id, "--groups", "/Kubernetes"]
      vb.memory = "2048"
      end
    end
  end
  
end
