all:
  hosts:
    master1:
      ansible_host: 10.0.0.11
      ip: 10.0.0.11
      access_ip: 10.0.0.11
    master2:
      ansible_host: 10.0.0.12
      ip: 10.0.0.12
      access_ip: 10.0.0.12
    worker1:
      ansible_host: 10.0.0.101
      ip: 10.0.0.101
      access_ip: 10.0.0.101
    worker2:
      ansible_host: 10.0.0.102
      ip: 10.0.0.102
      access_ip: 10.0.0.102
    worker3:
      ansible_host: 10.0.0.103
      ip: 10.0.0.103
      access_ip: 10.0.0.103
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
    kube_node:
      hosts:
        master1:
        master2:
        worker1:
        worker2:
        worker3:
    etcd:
      hosts:
        master1:
        master2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
